<?php
    class Six_Blog {
        
        public function __construct() {
            if (!is_admin()) {
                
            }
        }

        public function update_content($content) {
            $has_blog_shortcode = (strpos($content, 'data="blog"') !== false);
            $post_type = get_post_type();
            
            // Check if current post type is a blog entry
            if (is_single()) {
                if ($post_type == 'post') {
                    // Automatically update content if NO 'blog' shortcode exists in post content
                    if ($has_blog_shortcode == false) {
                        $lines = explode("\n", $content);
                        $total = count($lines);
                        $percentage = 30 / 100; // 30% of page
                        $index = ceil($total * $percentage);
        
                        // Add featured shortcode if more than 1 line exists
                        if (!empty($lines)) {
                            array_splice($lines, $index, 0, '[six data="blog" type="featured" category="Featured Content"]'); // Insert separator HTML
                            $content = implode("\n", $lines); // Convert array back to string
                        }

                    }

                    // Add social links to the side of the website
                    $content .= Six_Blog::get_share_links();
                }
            }

            // Return new content value
            return $content;
        }

        public static function get_random_post_by_category($category_name = '') {
            // Get category term_id
            $categories = get_categories();
            $name = '';
            $term_id = 0;

            // Loop through all possible categories for term id
            foreach ($categories as $category) {
                $name = $category->name;
                $term_id = $category->term_id;
                if ($category_name == $name) break;
            }
            
            // Return random post
            $posts = get_posts(
                array(
                    'numberposts'   => -1,
                    'category'      => $term_id,
                    'orderby'       => 'rand',
                    'order'         => 'DESC'
                )
            );
            return $posts[0]; // Return first random post
        }

        public static function get_featured_post_html($post) {
            // Load CSS if post is requested
            wp_enqueue_style('featured-post');

            // Popular featured post data
            $comment = '';
            $thumbnail = get_the_post_thumbnail_url($post->ID, 'medium');
            $content = substr(wp_strip_all_tags($post->post_content, true), 0, 150);
            $link = get_post_permalink($post->ID);
            $title = $post->post_title;
            
            // Add instructions for admin users
            if (current_user_can('edit_pages') == true) {
                $comment = '
                    <div class="featured-comment">
                        Need to move this featured post? Click <a href="/wp-admin/post.php?post=' . get_the_ID() . '&action=edit">Edit Post</a> and add or edit the following shortcode: 
                        <strong>[six data="blog" type="featured" category="Featured Content"]</strong>
                    </div>
                ';
            }
            
            // Update HTML output string
            $html = '
                <div class="featured-post row" data-comment="Generated by child theme: class-blog.php">' .
                    $comment . '
                    <div class="col left">
                        <div class="thumbnail" style="background-image: url(' . $thumbnail . ');"></div>
                    </div>
                    <div class="col right">
                        <h5>' . $title . '</h5>
                        <p>' . $content . '...</p>
                        <a class="link" href="' . $link . '">Read more</a>
                    </div>
                </div>
            ';

            return $html;
        }

        public static function get_share_links() {
            $post = get_post();
            $link = get_permalink();
            $title = get_the_title();
            $links = '
                <!--To update these links, edit /wp-content/themes/Divi-Child/php/class-blog.php -->
                <ul class="share-post vertical">
                    <li><a href="javascript:window.print()" aria-label="print"><img src="/wp-content/themes/Divi-Child/img/social/icon-circle-print.svg"></a></li>
                    <li><a href="mailto:?subject=Check out this post from Six Degrees!&body=I found this post from Six Degrees and thought you\'d enjoy it: ' . $link . '" target="_blank"><img src="/wp-content/themes/Divi-Child/img/social/icon-circle-mail.svg"></a></li>
                    <li><a href="https://pinterest.com/pin/create/link/?url=' . $link . '&description=' . $title . '" target="_blank"><img src="/wp-content/themes/Divi-Child/img/social/icon-circle-pinterest.svg"></a></li>
                    <li><a href="https://twitter.com/intent/tweet?text=' . $title . '&url=' . $link . '" target="_blank"><img src="/wp-content/themes/Divi-Child/img/social/icon-circle-twitter.svg"></a></li>
                    <li><a href="https://www.linkedin.com/shareArticle?mini=true&url=' . $link . '&title=' . $title . '" target="_blank"><img src="/wp-content/themes/Divi-Child/img/social/icon-circle-linkedin.svg"></a></li>
                    <li><a href="https://www.facebook.com/dialog/share?app_id=357999025266747&display=popup&href=' . $link . '" target="_blank"><img src="/wp-content/themes/Divi-Child/img/social/icon-circle-facebook.svg"></a></li>
                </ul>
                <style>
                    .share-post { list-style: none !important; padding: 0 !important; display: flex; flex-direction: column; line-height: initial !important; align-items: flex-start; position: fixed; bottom: 5%; left: 2% }
                    .share-post li { padding: 12px 0 0 0; transition: all 0.25s ease-in-out; }
                    .share-post li:hover { opacity: 0.5; }
                    .share-post li a img { display: block; }

                    @media print {
                        .share-post { display: none !important; }
                    }
                </style>
            ';
            return $links;
        }
    }
?>